name: Update RSS

on:
  push:
  schedule:
    - cron: "0 8 * * *"

jobs:
  update_readme:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.1'
      - name: Install dependencies
        run: go install cmd/gohumble.go
      - name: Run gohumble
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        run: cd public && gohumble
      - uses: stefanzweifel/git-auto-commit-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
        with:
          commit_message: Update RSS feeds using GitHub Workflow
          branch: main
